# Generated by Django 2.2 on 2020-06-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='Difficulty',
            new_name='difficulty',
        ),
    ]
