# Generated by Django 2.2 on 2020-06-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200620_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('H', 'Hard'), ('M', 'Medium'), ('E', 'Easy')], default='F', max_length=10),
        ),
    ]
