# Generated by Django 2.2 on 2020-06-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200620_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz_id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='questionwisequizscore',
            old_name='user_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='questionwisequizscore',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='user_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='scoreboard',
            old_name='user_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='scoreboard',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
