# version for docker compose
version: '3'

services: 
    # service of oour project here is 'web'
    web:
        # building current folder
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        # putting all our data in the container inside /app so that when we destroy the container our data won't lost 
        volumes: 
            - .:/app
        ports: 
            - "8000:8000"
        depends_on:
            - db

    db:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432" 
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.db
    
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        volumes:
            - static_volume:/app/web/static
            - media_volume:/app/web/media
        depends_on:
            - web

volumes: 
    postgres_data:
    static_volume:
    media_volume: